name: Run Postman Tests

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run postman/your-collection-file.json --env-var "apiKey=${{ secrets.POSTMAN_API_KEY }}"
        # Add -e for environment file if needed
        # run: newman run postman/your-collection-file.json -e postman/your-environment-file.json
